name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    container: clojure:temurin-17-tools-deps-1.11.1.1165
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            /root/.m2
            /root/.gitlibs
          key: test-${{ hashFiles('deps.edn') }}
          restore-keys: test-
      - run: clojure -X:dev:test
      - run: clojure -X:dev:doc
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
